name: Prune Stale Branches
description: A GitHub Action that can be used to prune/cleanup stale and/or unused branches in a repository.
author: Liatrio
branding:
  icon: heart
  color: green

inputs:
  github-token:
    description: The API token used to authenticate with GitHub.
    required: true

  stale-branch-age:
    description: |
      The amount and unit of time ([value] [unit]) until a branch is considered
      stale and flagged for deletion. The default is "30 days".
    required: true
    default: 30 days

  stale-branch-issue-age:
    description: |
      The amount and unit of time ([value] [unit]) to wait after creating a
      deletion issue before actually deleting the branch. Default is "7 days".
    required: true
    default: 7 days

runs:
  using: node20
  main: dist/index.js
